language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

dist: xenial
sudo: false

cache: pip

install:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt

script:
  - pytest -v
